id = "warplabs"
name = "WarpLabs"
version = "0.13.0"
schema_version = 1
authors = ["WarpLabs Team"]
description = "WFL, WFS, WPL, OML, WFG, and GXL language support for WarpLabs"
repository = "https://github.com/wp-labs/zed-warplabs"

[language_servers.wplabs-lsp]
name = "WarpLabs LSP"
languages = ["WFL", "WFS", "WPL", "OML", "WFG"]

[language_servers.wplabs-lsp.language_ids]
"WFL" = "wfl"
"WFS" = "wfs"
"WPL" = "wpl"
"OML" = "oml"
"WFG" = "wfg"

[grammars.wfl]
repository = "https://github.com/wp-labs/tree-sitter-wfl"
rev = "540c47074c56c8c6a118c4c9c23706609ee54c51"

[grammars.wfs]
repository = "https://github.com/wp-labs/tree-sitter-wfs"
rev = "f6f88ca4601ee043d2b3b1c6cc6f8a7e5d7d9574"

[grammars.wpl]
repository = "https://github.com/wp-labs/tree-sitter-wpl"
rev = "33d4aa48d8998682bc420b8fba36f7db7e8960d4"

[grammars.oml]
repository = "https://github.com/wp-labs/tree-sitter-oml"
rev = "dc7d189af25962650b7e828bbc34964b481674d0"

[grammars.wfg]
repository = "https://github.com/wp-labs/tree-sitter-wfg"
rev = "d60dcd01183611bb0f89af79c0e948ce803a65bf"

[grammars.gxl]
repository = "https://github.com/wp-labs/tree-sitter-gxl"
rev = "f50b33cd9f7c267c81569859189d88dde9511727"
