id = "warplabs"
name = "WarpLabs"
version = "0.12.0"
schema_version = 1
authors = ["WarpLabs Team"]
description = "WFL, WFS, WPL, OML, WFG, and GXL language support for WarpLabs"
repository = "https://github.com/wp-labs/zed-warplabs"

[language_servers.wplab-lsp]
name = "WarpLabs LSP"
languages = ["WFL", "WFS", "WPL", "OML", "WFG"]

[language_servers.wplab-lsp.language_ids]
"WFL" = "wfl"
"WFS" = "wfs"
"WPL" = "wpl"
"OML" = "oml"
"WFG" = "wfg"

[grammars.wfl]
repository = "https://github.com/wp-labs/tree-sitter-wfl"
rev = "02edbcd29a8e94c2e0257e3f857304ca544b5113"

[grammars.wfs]
repository = "https://github.com/wp-labs/tree-sitter-wfs"
rev = "f6f88ca4601ee043d2b3b1c6cc6f8a7e5d7d9574"

[grammars.wpl]
repository = "https://github.com/wp-labs/tree-sitter-wpl"
rev = "33d4aa48d8998682bc420b8fba36f7db7e8960d4"

[grammars.oml]
repository = "https://github.com/wp-labs/tree-sitter-oml"
rev = "a950b958c38d6826f334acbb8c0a1a793997151b"

[grammars.wfg]
repository = "https://github.com/wp-labs/tree-sitter-wfg"
rev = "16edb9947d8ce65b1f25ddd3cb3f142364c5e7dd"

[grammars.gxl]
repository = "https://github.com/wp-labs/tree-sitter-gxl"
rev = "0461ca5d088fc64af8222d1cdadeb2070111c3e5"
