name = "WPL"
grammar = "wpl"
path_suffixes = ["wpl"]
brackets = [
  { start = "{", end = "}", close = true, newline = true },
  { start = "(", end = ")", close = true, newline = false },
  { start = "[", end = "]", close = true, newline = false },
  { start = "<", end = ">", close = true, newline = false },
  { start = "\"", end = "\"", close = true, newline = false, not_in = ["string"] },
]
autoclose_before = ";:.,=}])> \n\t"
word_characters = ["_", "@", "/"]
